services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
    ports:
      - "8543:80" # Webhook endpoint
      - "9120:9120" # Prometheus metrics
    environment:
      TZ: Europe/London
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco-data:/data
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/v1/health" ]  
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  doco-data:
